In [ ]:
import numpy as np
import pandas as pd

In [ ]:
!gdown 1Etdl87T1Ab711XGxIXQID0wHxi7YMLRj

Downloading...
From: https://drive.google.com/uc?id=1Etdl87T1Ab711XGxIXQID0wHxi7YMLRj
To: /content/Pfizer_1.csv
100% 1.51k/1.51k [00:00<00:00, 8.73MB/s]

In [ ]:
df = pd.read_csv("Pfizer_1.csv")

In [ ]:
df.shape

(18, 15)

In [ ]:
df.head(3)

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25

In [ ]:
pd.melt(df,id_vars=['Date',	'Drug_Name',	'Parameter'])

           Date                Drug_Name    Parameter  variable  value
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00   23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00   12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00    NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00    NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00   24.0
..          ...                      ...          ...       ...    ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00   14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00   23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00   28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00   24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00   15.0

[216 rows x 5 columns]

In [ ]:
df2 = pd.melt(df,id_vars=['Date',	'Drug_Name',	'Parameter']).rename(columns={'variable':'time','value':'reading'})
df2

           Date                Drug_Name    Parameter      time  reading
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00     23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00     12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00      NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00      NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00     24.0
..          ...                      ...          ...       ...      ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00     14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00     23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00     28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00     24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00     15.0

[216 rows x 5 columns]

In [ ]:
pd.pivot(df2,index=['Date',	'Drug_Name','time'],columns='Parameter',values='reading')

Parameter                                    Pressure  Temperature
Date       Drug_Name               time
15-10-2020 diltiazem hydrochloride 10:30:00      18.0         20.0
                                   11:30:00      19.0         20.0
                                   12:30:00      20.0         21.0
                                   1:30:00       12.0         23.0
                                   2:30:00       13.0         22.0
...                                               ...          ...
17-10-2020 ketamine hydrochloride  5:30:00       11.0         17.0
                                   6:30:00       12.0         18.0
                                   7:30:00       12.0         19.0
                                   8:30:00       11.0         20.0
                                   9:30:00       12.0         21.0

[108 rows x 2 columns]

In [ ]:
df3 = (pd.pivot(df2,index=['Date',	'Drug_Name','time'],columns='Parameter',values='reading')
.reset_index()
)

In [ ]:
df3['Date'].unique()

array(['15-10-2020', '16-10-2020', '17-10-2020'], dtype=object)

In [ ]:
df3

Parameter,Date,Drug_Name,time,Pressure,Temperature
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0
...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         108 non-null    object
 1   Drug_Name    108 non-null    object
 2   time         108 non-null    object
 3   Pressure     95 non-null     float64
 4   Temperature  95 non-null     float64
dtypes: float64(2), object(3)
memory usage: 4.3+ KB

In [ ]:
s1 = pd.Series([1,2,None,4,5,np.nan])
s1

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
dtype: float64

In [ ]:
~s1.isna()

0     True
1     True
2    False
3     True
4     True
5    False
dtype: bool

In [ ]:
d1 = pd.DataFrame([[10,20],[None,40],[30,np.nan]])
d1

      0     1
0  10.0  20.0
1   NaN  40.0
2  30.0   NaN

In [ ]:
d1.isna()

       0      1
0  False  False
1   True  False
2  False   True

In [ ]:
mask = ~df3['Pressure'].isna()
mask

0      True
1      True
2      True
3      True
4      True
       ...
103    True
104    True
105    True
106    True
107    True
Name: Pressure, Length: 108, dtype: bool

In [ ]:
df3.loc[mask,]

Parameter,Date,Drug_Name,time,Pressure,Temperature
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0
...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0

In [ ]:
df3[mask]

Parameter,Date,Drug_Name,time,Pressure,Temperature
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0
...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0